import "~/styles/globals.css";

import { GeistSans } from "geist/font/sans";
import { type Metadata } from "next";

import { TRPCReactProvider } from "~/trpc/react";
import { Header } from "./_components/header";
import { Toaster, toast } from 'sonner'

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={`${GeistSans.variable}`}>
      <head>  <meta name="viewport" content="width=device-width, initial-scale=1.0" /></head>
      <body>
      <Toaster />        
        <TRPCReactProvider>
          <Header />
          {children}        
        </TRPCReactProvider>
      </body>
    </html>
  );
}
